<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="3" tests="4" name="Command line test" time="0.049" errors="0" timestamp="2023-04-03T20:13:43 ALMT">
  <testcase classname="CalculatorTest" name="addTwoNumsTest" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at CalculatorTest.addTwoNumsTest(CalculatorTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- addTwoNumsTest -->
  <testcase classname="CalculatorTest" name="test123" time="0.001">
    <failure type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
at CalculatorTest.test123(CalculatorTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- test123 -->
  <testcase classname="CalculatorTest" name="testAssertTrue" time="0.001"/>
  <testcase classname="CalculatorTest" name="testSoftAssert" time="0.006">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [5] but found [4],
	expected [6] but found [4],
	expected [7] but found [4],
	expected [8] but found [4]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [5] but found [4],
expected [6] but found [4],
expected [7] but found [4],
expected [8] but found [4]
at CalculatorTest.testSoftAssert(CalculatorTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testSoftAssert -->
</testsuite> <!-- Command line test -->
